# name of pipeline
name: Vercel Preview Deployment 

# define env
env: 
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
# to trigger the workflow directly
on:
    push:
        paths:
            - 'ReportEmotionForm/**'
        branches-ignore:
            - main

jobs: 
    Deploy-Preview:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ../ReportEmotionForm
        steps: 
            - uses: actions/setup-node@v2
              with:
                node-version: '20'

            - name: Install Vercel CLI
              run: npm install --global vercel
            
            - name: Install Angular CLI
              run: npm install -g @angular/cli

            - name: Build Angular Project
              run: |
                npm install
                ng build

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN}}

            - name: Deploy Project Artifacts 
              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}